initial commit

diff --git a/backend/Jenkinsfile b/backend/Jenkinsfile
--- a/backend/Jenkinsfile
+++ b/backend/Jenkinsfile
@@ -1,27 +1,67 @@
 pipeline {
-    
     agent any
-    
+
     environment {
-  EC2_IP = "44.216.122.26"
+        EC2_IP = "44.216.122.26"
     }
-  stages 
-  {
-  stage('checkout code')
-  {
-    steps 
-    {
-      git branch = "main",
-      credientialId = "mern-stacks09233git",
-      url = "https://github.com/kaviyarashugayu1997-maker/fullstack_project.git"
+
+    stages {
+        stage('Checkout Code') {
+            steps {
+                git branch: 'main',
+                    credentialsId: 'mern-stacks09233git',
+                    url: 'https://github.com/kaviyarashugayu1997-maker/fullstack_project.git'
+            }
+        }
+
+        stage('Build & Test') {
+            steps {
+                dir('backend') {
+                    sh 'npm install'
+                }
+            }
+        }
+
+        stage('Deploy to EC2') {
+            steps {
+                sshagent(['mernstack-backend']) {
+                    sh '''
+                    shh -o StrictHostKeyChecking=no ubuntu@${EC2_IP} << EOF
+set -e
+mkdir -p /home/ubuntu/apps
+cd /home/ubuntu/apps
+
+if [ ! -d "fullstack_project" ]; then
+    git clone https://github.com/kaviyarashugayu1997-maker/fullstack_project.git
+fi
+
+cd fullstack_project
+git fetch origin
+git checkout main
+git pull origin main
+
+cd backend
+
+docker stop myapp || true
+docker rm myapp || true
+
+docker build -t backend-image .
+docker run -d -p 5001:5000 --name myapp backend-image
+
+EOF
+                    """
+                }
+            }
+        }
     }
-  }
-stage('build') {
-  steps {
-      script
-      {
-          sh 'docker build -t image .'
-      }
-    
-  }
-}}
+
+    post {
+        success {
+            echo "DEPLOYMENT SUCCESSFUL: http://${EC2_IP}:5001"
+        }
+        failure {
+            echo "DEPLOYMENT FAILED"
+        }
+    }
+}
+
